version: '3.7'

services:
  client:
    build: 
      context: ./client/
      dockerfile: Dockerfile
    container_name: rt-nginx-react
    # ports: 
    #   - 80:80
    #   - 443:443
    volumes: 
      - client/ssl:/etc/nginx/certs
    network_mode: host
    
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: rt-express-socket
    # ports:
    #   - 3001:3001
    #   - 27017:27017
    #   - 6379:6379
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    network_mode: host
    



volumes:
  data:
    driver: local